config/routes.rb
Rails.application.routes.draw do
  root to: "blogs#index"

  resources :blogs 

  get "/mypage/:id", to: "users#show", as: "user_mypage"
  resources :users, path_names: { new: 'sign_up' }
  
  resources :sessions, path_names: { new: 'sign_in' }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_secure_password

  validates :password, presence: true,
                       length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private
  def login_required
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  skip_before_action :login_required, only: [:index]
  
  def index
    @blogs = Blog.all
  end

  def show; end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  def new
    @blog = Blog.new
  end

  def edit; end
  
  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to blogs_url, notice: 'ブログを投稿しました！'
    else
      flash.now[:danger] = "ブログ投稿に失敗しました！"
      render :new
    end
  end
  
  def update
    if current_user.blogs.update(blog_params)
      redirect_to @blog, notice: 'ブログを編集しました！'
    else
      flash.now[:danger] = "ブログの編集に失敗しました！"
      render :edit
    end
  end
  
  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new; end

  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_mypage_path(user.id), notice: "ログインに成功しました！"
    else
      flash.now[:danger] = "ログインに失敗しました！"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path, notice: "ログアウトしました！"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only: [:edit, :update, :show, :destroy]
  skip_before_action :login_required,only: [:new, :create]

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_mypage_path(@user.id), notice: "ユーザーを登録しました！"
    else
      flash.now[:danger] = "ユーザー登録に失敗しました！"
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_mypage_path(@user.id), notice: "ユーザー情報を更新しました！"
    else
      flash.now[:danger] = "ユーザー情報の更新に失敗しました！"
      render :edit
    end
  end

  def show; end

  def destroy
    session.delete(:user_id)
    @user.destroy
    redirect_to new_session_path, notice: "ユーザーを削除しました！"
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_params
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/blog/new.html.erb
<h1>ブログ作成</h1>
<%= form_with(model: Blog.new, local: true) do |form| %>
  <%= form.label :ブログを作成してください %><br>
  <%= form.text_field :content %><br><br>
  <%= form.submit %>
<% end %>
</div>

app/views/blogs/_form.html.erb
<div class="form">
  <h1><%= @headline %></h1>
  <%= form_with(model: @blog, local: true) do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<% @headline = "ブログ編集" %>
<%= render "form" %>

app/views/blogs/index.html.erb
<div class="form">
  <h1>ブログ一覧</h1>
  <table>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th>投稿者</th>
      </tr>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to blog.title, blog_path(blog.id) %></td>
        <td><%= blog.content %></td>
        <td><%= blog.user.name %></td>
      </tr>
    <% end %>
  </table>

  <%= link_to '投稿', new_blog_path, class: 'btn btn-primary' %>
</div>

app/views/blogs/new.html.erb
<% @headline = "ブログ作成" %>
<%= render "form" %>

app/views/blogs/show.html.erb
<div class="form">
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
  <%= link_to '編集', edit_blog_path(@blog.id) ,class: 'btn btn-success'%>
  <%= link_to '削除', blog_path(@blog.id), method: :delete, data: {confirm: "削除しますか？"} , class: 'btn btn-danger'%>
</div>

app/views/common/_error.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= model.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <%= render "shared/header" %>
      <div id="cotainer">
        <%= yield %>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
  
</html>

app/views/shared/_footer.html.erb
<footer>
  <p>&copy; 2020 MTEK Team</p>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <% if logged_in? %>
    <div class="loggin">
      <%= link_to "プロフィール", user_mypage_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
      <%= link_to "ブログ一覧", blogs_path %>
    </div>
  <% else %>
    <div class="guest">
      <%= link_to "ログイン", new_session_path %>
      <%= link_to "サインアップ", new_user_path %>
      <%= link_to "ブログ一覧", blogs_path %>
    </div>
  <% end %>
</header>

<div class="header_flash">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: key) %>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="form">
<%= render "common/error", model: @user %>
  <h1><%= @headline %></h1>
  <%= form_with(model: @user ,local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/users/edit.html.erb
<% @headline = "マイページ編集" %>
<%= render 'form' %>

app/views/users/new.html.erb
<% @headline = "サインアップ" %>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="user_show">
  <h1>マイページ</h1>
  <p><%= @user.name %></p>
  <p><%= @user.email %></p>
  <%= link_to "修正", edit_user_path, class: 'btn btn-success' %>
  <%= link_to "削除", user_path(@user.id), method: :delete, data: { confirm: "削除しますか？"}, class: 'btn btn-danger' %>
</div>